import { Locale } from 'date-fns';

export const dateFnsLocaleMap: Record<string, () => Promise<Locale>> = {
  'ar': () => import('date-fns/locale/ar').then(({ ar }) => ar),
  'bg': () => import('date-fns/locale/bg').then(({ bg }) => bg),
  'ca': () => import('date-fns/locale/ca').then(({ ca }) => ca),
  'cs': () => import('date-fns/locale/cs').then(({ cs }) => cs),
  'da': () => import('date-fns/locale/da').then(({ da }) => da),
  'de': () => import('date-fns/locale/de').then(({ de }) => de),
  'el': () => import('date-fns/locale/el').then(({ el }) => el),
  'en-GB': () => import('date-fns/locale/en-GB').then(({ enGB }) => enGB),
  'es': () => import('date-fns/locale/es').then(({ es }) => es),
  'fa': () => import('date-fns/locale/fa-IR').then(({ faIR }) => faIR),
  'fr': () => import('date-fns/locale/fr').then(({ fr }) => fr),
  'he': () => import('date-fns/locale/he').then(({ he }) => he),
  'hi': () => import('date-fns/locale/hi').then(({ hi }) => hi),
  'hr': () => import('date-fns/locale/hr').then(({ hr }) => hr),
  'hu': () => import('date-fns/locale/hu').then(({ hu }) => hu),
  'id': () => import('date-fns/locale/id').then(({ id }) => id),
  'it': () => import('date-fns/locale/it').then(({ it }) => it),
  'ja': () => import('date-fns/locale/ja').then(({ ja }) => ja),
  'ko': () => import('date-fns/locale/ko').then(({ ko }) => ko),
  'lt': () => import('date-fns/locale/lt').then(({ lt }) => lt),
  'lv': () => import('date-fns/locale/lv').then(({ lv }) => lv),
  'ms': () => import('date-fns/locale/ms').then(({ ms }) => ms),
  'nl': () => import('date-fns/locale/nl').then(({ nl }) => nl),
  'pl': () => import('date-fns/locale/pl').then(({ pl }) => pl),
  'pt': () => import('date-fns/locale/pt').then(({ pt }) => pt),
  'pt-BR': () => import('date-fns/locale/pt-BR').then(({ ptBR }) => ptBR),
  'ro': () => import('date-fns/locale/ro').then(({ ro }) => ro),
  'ru': () => import('date-fns/locale/ru').then(({ ru }) => ru),
  'sr': () => import('date-fns/locale/sr').then(({ sr }) => sr),
  'sv': () => import('date-fns/locale/sv').then(({ sv }) => sv),
  'th': () => import('date-fns/locale/th').then(({ th }) => th),
  'tr': () => import('date-fns/locale/tr').then(({ tr }) => tr),
  'uk': () => import('date-fns/locale/uk').then(({ uk }) => uk),
  // 'ur': () => import('date-fns/locale/ur').then(({ ur }) => ur),
  'vi': () => import('date-fns/locale/vi').then(({ vi }) => vi),
  'zh-CN': () => import('date-fns/locale/zh-CN').then(({ zhCN }) => zhCN),
  'zh-TW': () => import('date-fns/locale/zh-TW').then(({ zhTW }) => zhTW),
};
