<?php

return [
  'en' => 'en',
  'en-US' => 'en',
  'en-GB' => 'en-GB',
  'hu' => 'hu',
  'ms' => 'ms',
  'sr' => 'sr_Latn',
  'id' => 'en',
  'bg' => 'en',
  'zh-CN' => 'en',
  'zh-TW' => 'en',
  'hr' => 'en',
  'cs' => 'en',
  'da' => 'en',
  'nl' => 'en',
  'fi' => 'en',
  'fr' => 'en',
  'de' => 'en',
  'el' => 'en',
  'hi' => 'en',
  'it' => 'en',
  'ja' => 'en',
  'ko' => 'en',
  'lt' => 'en',
  'no' => 'en',
  'pl' => 'en',
  'pt-BR' => 'en',
  'ro' => 'en',
  'ru' => 'en',
  'es-ES' => 'en',
  'es-419' => 'en',
  'sv-SE' => 'en',
  'th' => 'en',
  'tr' => 'en',
  'uk' => 'en',
  'vi' => 'en',
];
