<?php

/**
 * Mapping of language names to app locales
 */
return [
  'en-US' => 'en',
  'en-GB' => 'en-GB',
  'hu' => 'hu',
  'ms' => 'ms',
  'sr' => 'sr_Latn',
  'id' => 'id',
  'bg' => 'bg',
  'zh-CN' => 'zh-CN',
  'zh-TW' => 'zh-TW',
  'hr' => 'hr',
  'cs' => 'cs',
  'da' => 'da',
  'nl' => 'nl',
  'fi' => 'fi',
  'fr' => 'fr',
  'de' => 'de',
  'el' => 'el',
  'hi' => 'hi',
  'it' => 'it',
  'ja' => 'ja',
  'ko' => 'ko',
  'lt' => 'lt',
  'no' => 'no',
  'pl' => 'pl',
  'pt-BR' => 'pt-BR',
  'ro' => 'ro',
  'ru' => 'ru',
  'es-ES' => 'es',
  'es-419' => 'es-419',
  'sv-SE' => 'sv',
  'th' => 'th',
  'tr' => 'tr',
  'uk' => 'uk',
  'vi' => 'vi',
];
