<?php

/**
 * Mapping of router language names to app locales
 */
return [
  /**
   * Only used by the UI
   */
  'supported_locales' => [
    'ar',
    'bg',
    'ca',
    'zh',
    'zh-TW',
    'hr',
    'cs',
    'nl',
    'en-GB',
    'en',
    'fr',
    'de',
    'el',
    'hi',
    'he',
    'hu',
    'id',
    'it',
    'ja',
    'ko',
    'lv',
    'lt',
    'ms',
    'mn',
    'fa',
    'pl',
    'pt',
    'pt-BR',
    'ro',
    'ru',
    'sr',
    'es',
    'sv',
    'th',
    'tr',
    'uk',
    'ur',
    'vi',
    'da',
    'nb',
  ],
  'locale_route_alias' => [
    'en_US' => 'en',
    'en_GB' => 'en-GB',
    'es-ES' => 'es',
    'sv-SV' => 'sv',
    'pt_BR' => 'pt-BR',
    'zh_CN' => 'zh',
    'zh-CN' => 'zh',
  ],
  /**
   * Maps languages on the UI/router level to the corresponding application locale
   */
  'ui_locale_map' => [
    'ar' => 'ar',
    'bg' => 'bg',
    'ca' => 'ca',
    'cs' => 'cs',
    'da' => 'da',
    'de' => 'de',
    'el' => 'el',
    'en-GB' => 'en_GB',
    'en' => 'en',
    'es' => 'es',
    'fa' => 'fa',
    'fi' => 'fi',
    'fr' => 'fr',
    'he' => 'he',
    'hi' => 'hi',
    'hr' => 'hr',
    'hu' => 'hu',
    'id' => 'id',
    'it' => 'it',
    'ja' => 'ja',
    'ko' => 'ko',
    'lt' => 'lt',
    'lv' => 'lv',
    'ms' => 'ms',
    'nl' => 'nl',
    'no' => 'no',
    'pl' => 'pl',
    'pt' => 'pt',
    'pt-BR' => 'pt_BR',
    'ro' => 'ro',
    'ru' => 'ru',
    'sr' => 'sr_Latn',
    'sv' => 'sv',
    'th' => 'th',
    'tr' => 'tr',
    'uk' => 'uk',
    'ur' => 'ur',
    'vi' => 'vi',
    'zh' => 'zh_CN',
    'zh-TW' => 'zh_TW',
  ],
];
