name: Translation credits updater

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ci-i18n-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-i18n-credits:
    name: 'Update i18n credits'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          version: 11

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '24'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Re-generate translation credits
        run: pnpm run generate-translation-credits
        env:
          APP_URL: ${{ vars.APP_URL }}
          APP_CONSOLE_USER_TOKEN: ${{ secrets.APP_CONSOLE_USER_TOKEN }}

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7
        with:
          commit_message: Update translation credits
          file_pattern: 'README.md lang/*.json'
